### ISSUE TITLE
Error: Failed creating the event tap

### ISSUE THREAD

**Issue by tandrewnichols** [dagit/annelid#10]
I just updated to the latest release, and now I get this when launching annelid.

<img width="372" alt="Screenshot 19" src="https://user-images.githubusercontent.com/2755760/229364033-de954232-a45a-45c1-b62e-7e66d17bcc67.png">

It doesn't seem to break anything - I can hit okay and continue and everything works as expected (at least as far as I can tell). But I do get it _every time_ I start up annelid.

**Comment by dagit** [comment]
I assume this is related to the issues you're having with hotkeys, but I'm not certain as I don't know the mac stuff very well.

**Comment by tandrewnichols** [comment]
Maybe I need to try removing annelid and reinstalling. I'm wondering if just replacing the existing installation didn't work (with accessibility for example).

**Comment by tandrewnichols** [comment]
I deleted annelid (and emptied trash) and removed it from accessibility and then reinstalled it but still see both this behavior and the keyboard shortcuts not working.

**Comment by tandrewnichols** [comment]
Ah, okay. I had forgotten that accessibility changes don't take affect until restarting the mac. So this issue went away and the numbers are working once I restarted.

**Comment by dagit** [comment]
Wow! I'm glad you figured out something that works.

Could I convince you to add a section to the README for macOS users that explains how to get it working based on your experience?

**Comment by tandrewnichols** [comment]
I can probably try to do that.
