### ISSUE TITLE
settings has etacoon spelled wrong. its etecoon

### ISSUE THREAD

**Issue by matthewclauzel** [dagit/annelid#22]
I know I sound like the grammar police but its etecoon. 
![image](https://github.com/dagit/annelid/assets/46776078/ed7cdd20-9f67-4d60-bb9a-d78aea220ebf)

**Comment by dagit** [comment]
I'm aware. It's spelled that way because that's how it's spelled in chabo's autosplitter which mine is based on: https://github.com/UNHchabo/AutoSplitters/blob/master/SuperMetroid/LiveSplit.SuperMetroid.asl#L142

I guess I could change it. It's probably a typo.

**Comment by dagit** [comment]
I just pushed a change to the dev branch that should allow either spelling but will default to etecoons when making a new config. So the next release (whenever that is, hopefully later today) should support the correct spelling.
