### ISSUE TITLE
Windows: Dark square when right clicking

### ISSUE THREAD

**Issue by ChTBoner** [dagit/annelid#27]
Hello,

(Even though I know Windows isn't the primary target)

Testing the latest release on Windows, I get black boxes when I right click:
![image](https://github.com/dagit/annelid/assets/14848356/6c40a9d4-8e82-4b0f-a773-f48990b62730)

You can hit me up on Discord if you want or need fast testing for a fix

**Comment by dagit** [comment]
Thanks for the bug report. I recently upgraded the egui version and I know it has had some release issues. I'll have to check if there is an update yet. That's the most likely cause, I think.

**Comment by dagit** [comment]
Have you had a chance to test the new release I made? I believe it fixes the issue. Thanks.
